name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

#     - shell: bash
#       name: Docker login
#       run: |
#         echo ${{ secrets.DOCKER_HUB_USERNAME }} | sed 's/./& /g'
#         docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Check Out Repo
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lkravi/golang-test:$(date +'%S')

